development:
  adapter: postgresql
  database: zleep_development_db
  host: localhost
  username: alicenguyen
  password: alicenguyen
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: zleep_test_db
  host: localhost
  username: alicenguyen
  password: alicenguyen
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: zleep_production_db
  host: localhost
  username: alicenguyen
  password: alicenguyen
  pool: 5
  timeout: 5000
